<a href="https://colab.research.google.com/github/kapilupadhyay06/Data-Analysis./blob/main/practice_12oct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Q-1. Create a Csv with no header and 5 column . Load it with yyour own column names and makes the first column index

In [1]:
import pandas as pd

In [2]:
data = [[1,"prakash", "AC2","bihar",38],
        [2,"Ansh", "AC1","jhansi",5],
        [3,"ravindra", "AC3","Mathura",48],
        [4,"shivesh", "AC3","odisha",50],
        [5,"yanshul", "AC3","iglass",65],
        ]
temp_df = pd.DataFrame(data)
temp_df.to_csv("data.csv", header=False, index=False)
custom_columns = ["Sno.", "Name", "sec", "City", "roll"]
df = pd.read_csv("data.csv", names=custom_columns, index_col=0)
df

          Name  sec     City  roll
Sno.
1      prakash  AC2    bihar    38
2         Ansh  AC1   jhansi     5
3     ravindra  AC3  Mathura    48
4      shivesh  AC3   odisha    50
5      yanshul  AC3   iglass    65

Q-2. write a file using ; as a delimiter and -999 for missing values. read it so -999 become NaN.

In [5]:
import numpy as np
import pandas as pd

content = """Sno.;Name;roll
1;Prakash;38
2;Ansh;-999
3;shivesh;48
4;ravindra;-999
5;yanshul;65"""

with open("custom_data.csv", "w") as f:
    f.write(content)

df = pd.read_csv("custom_data.csv", sep=";", na_values=-999)
df

   Sno.      Name  roll
0     1   Prakash  38.0
1     2      Ansh   NaN
2     3   shivesh  48.0
3     4  ravindra   NaN
4     5   yanshul  65.0

In [ ]:
# Q3. Read a big in chunks of 2,000 rows and compute yhe mean of one column per Key across all chunks

In [6]:
import pandas as pd
df = pd.read_csv("/content/titanic[1].csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [10]:
import pandas as pd

grouped_sums = pd.Series(dtype=float)
grouped_counts = pd.Series(dtype=int)

for chunk in pd.read_csv("/content/titanic[1].csv", chunksize=800):
    grouped_sums = grouped_sums.add(chunk.groupby("Pclass")["Fare"].sum(), fill_value=0)
    grouped_counts = grouped_counts.add(chunk.groupby("Pclass")["Fare"].count(), fill_value=0)

mean_fare_per_class = grouped_sums / grouped_counts
mean_fare_per_class

Pclass
1    84.154687
2    20.662183
3    13.675550
dtype: float64

# Expoty a DataFrame with orient = "records", read it back with pd.read_json , and check equality with .equals

In [11]:
import pandas as pd
df = pd.DataFrame({"Name": ["Prakash", "Ansh", "Ravindra"], "Age": [22, 21, 23]})
df.to_json("data.json", orient="records")
df_read = pd.read_json("data.json", orient="records")
print(df.equals(df_read))

True

In [ ]:
# write a shoort table by hand  and load it with read_html.

In [12]:
import pandas as pd

# Write a short HTML table string by hand
html_data = """
<table>
  <tr>
    <th>Name</th>
    <th>Roll</th>
    <th>City</th>
    </tr>
      <tr>
    <td>Prakash</td>
    <td>38</td>
    <td>Bihar</td>
        </tr>
      <tr>
       <td>Ansh</td>
    <td>5</td>
  <td>Jhansi</td>
  </tr>
 </table>
         """
dfs = pd.read_html(html_data)
df = dfs[0]
df

/tmp/ipykernel_952/1036616980.py:23: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html_data)

      Name  Roll    City
0  Prakash    38   Bihar
1     Ansh     5  Jhansi

In [18]:
import json

t = '''{
    "shop": "Fresh Mart","open": true,  "owner": null, "items": [
        {"name": "Rice", "price": 60, "qty": 10},
        {"name": "Oil", "price": 150, "qty": 4},
        {"name": "Tea", "price": 120, "qty": 6}  ]
}'''
#1
data = json.loads(t)
print(type(data))
#2
print(data["items"][1]["name"])
print(len(data["items"]))
#3
print(data["owner"])
#4
print(json.dumps(data,indent=2))

<class 'dict'>
Oil
3
None
{
  "shop": "Fresh Mart",
  "open": true,
  "owner": null,
  "items": [
    {
      "name": "Rice",
      "price": 60,
      "qty": 10
    },
    {
      "name": "Oil",
      "price": 150,
      "qty": 4
    },
    {
      "name": "Tea",
      "price": 120,
      "qty": 6
    }
  ]
}